### ISSUE TITLE
mw.emit() bug?

### ISSUE THREAD

**Issue by acketon** [HackPlan/quark-shell-mac#17]
I was testing the mw.on() and mw.emit() functions. I wanted the new window to send a message back to the main menubar window and the main window to send a message back to the new window. I was going to use this to send data to the new window after it is opened. 

The first message works good, just like your example. if I do this: 

```js
mw.on("TestMessage", function(message) {
        console.log(message)
        mw.emit("replymessage", "I can't Dave")
})
```

``mw.emit("replymessage", "I can't Dave");`` does not work unless I put it in a setTimeout of about half a second... Then it works. 

But after that I ran into a problem. If I close the New Window and then reopen it and run everything a second time, I get an error in the main window when trying to call mw.emit("replymessage", "I can't Dave") a second time. I removed the setTimeout stuff and just manually ran mw.emit() in the console and it also gave the error so it seems to be that mw.emit() can't be called to send a message to the new window anytime AFTER the first time the window is opened and closed. 

```
Error: TypeError: 'undefined' is not an object (evaluating 'func.apply')
xcode console error: 
2014-09-02 23:50:06.252 menubar-webkit[72917:303] JavaScript console: undefined:1: TypeError: 'undefined' is not an object (evaluating 'func.apply')
2014-09-02 23:50:06.253 menubar-webkit[72917:303] -[__NSArrayI addObject:]: unrecognized selector sent to instance 0x608000437ac0
```

Does that description make sense?

**Comment by xhacker** [comment]
Hi @acketon, can you confirm that this issue was fixed?
