### ISSUE TITLE
n00b-issue

### ISSUE THREAD

**Issue by basiclaser** [HackPlan/quark-shell-mac#32]
Hello! I love all your work, especially Pomotodo. I am trying to install quark, but when I run 'pod install' it fails with the following error. Is it a permissions problem or something? Thanks for the support. 

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:422:in `open': No such file or directory - /Users/chris/.cocoapods/repos (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:422:in `foreach'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:422:in `children'
	from /Users/chris/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:63:in `all'
	from /Users/chris/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:130:in `repo_information'
	from /Users/chris/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:34:in `report'
	from /Users/chris/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:58:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:300:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:274:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:264:in `run'
	from /Users/chris/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
	from /Users/chris/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'

**Comment by xhacker** [comment]
Can you try `pod setup` then `pod install`?

**Comment by basiclaser** [comment]
That got it! Amazing, thank you. Will share what I've made with you soon.

**Comment by xhacker** [comment]
Looking forward to seeing your creation :)
