### ISSUE TITLE
Deploy to windows environment

### ISSUE THREAD

**Issue by basiclaser** [HackPlan/quark-shell-mac#34]
Hi there, are there any current builds for windows? Or is it on your to do list?

**Comment by orzFly** [comment]
Our [Pomotodo for Windows](https://pomotodo.com/apps) has already shipped with a custom build of Atom-Shell which is a compatibility layers to bring QuarkShell apps to Windows.

At this moment it's too complex to build. Also, it was originally intended for Pomotodo. I have to make it much more general before releasing to the public.

**Comment by basiclaser** [comment]
great, I really look forward to it! You should maybe change the quark-shell-mac README to reflect this, because it sounds like it is already available.

Thanks

**Comment by xhacker** [comment]
@basiclaser: fair enough, I'm going to change README a little.

**Comment by basiclaser** [comment]
Really, amazing work so far though, thanks really.
Hands down my favourite Github project as a web developer.
