### ISSUE TITLE
window 'popup' dimensions

### ISSUE THREAD

**Issue by basiclaser** [HackPlan/quark-shell-mac#35]
I appreciate that maybe this question is out of the scope of what you are offering, but thought I would ask anyway. Which variables should I change to modify the size of the main pop-up window? I was chasing after NSwindow, setFrame, NSWidth, but couldn't figure it out. 

Thanks again for your help!

**Comment by xhacker** [comment]
We will add customizations some day (as in #20), but currently you can open `MainMenu.xib` and resize both the window and the webview. Let me know if it works.

**Comment by basiclaser** [comment]
This worked perfectly, thankyou!
