### ISSUE TITLE
Tab-able apps? 

### ISSUE THREAD

**Issue by basiclaser** [HackPlan/quark-shell-mac#36]
Hi there, would it be possible to expose our quark applications to the 'active application' tab, so that users can CMD-tab to access the application? 

Thank you very much for your ongoing support.

**Comment by xhacker** [comment]
Quark Shell is currently focusing on menubar apps, is it necessary to have Cmd-tab support?

**Comment by basiclaser** [comment]
It's certainly not necessary, just an interesting option. Thanks for the info.

**Comment by xhacker** [comment]
@basiclaser: Yeah we may implement it in the future.
