### ISSUE TITLE
setupPreferences Label

### ISSUE THREAD

**Issue by hovancik** [HackPlan/quark-shell-mac#38]
It would be really nice to be able to set different Label vs Window name on Preferences

eg: 
`"label": "General"` as set in setupPreferencesm but the window name would be taken from `<title>` tag

**Comment by xhacker** [comment]
What's the use case of this feature? I thought all Mac apps use the label as window title in Preferences.

**Comment by hovancik** [comment]
Well, I guess it's my personal taste...

Let's say  I have 'Twitter'. I feel like I wanna see there 'Twitter Preferences' as window title.

**Comment by xhacker** [comment]
I don't think it's really necessary, and I don't want to hack into the third-party library (using the label as window title is the default behavior of [RHPreferences](https://github.com/heardrwt/RHPreferences)). Sorry about that.

If you really think it's necessary you could fork the repo and see if you could do something with https://github.com/heardrwt/RHPreferences/blob/master/RHPreferences/RHPreferencesWindowController.h#L52.

**Comment by hovancik** [comment]
cool, no problem, if it's default behavior I am fine with that.
