### ISSUE TITLE
可以将html文件等放到.app外部吗?

### ISSUE THREAD

**Issue by w88975** [HackPlan/quark-shell-mac#40]
比如在首次运行的时候，会在磁盘创建一个文件夹，将html复制到硬盘里，以后的每次操作都从硬盘读取。

这样做的目的是，我希望我开发的app可以管理和加载包，将package放到硬盘某个位置，每次运行前加载所有包。

与此同时，需要一个IO操作，删除和创建文件，读取文本文件这些简单的操作。

希望能够加上，谢谢

**Comment by xhacker** [comment]
第一个需求你可以试试用符号连接。

第二个需求有点麻烦，因为 Quark Shell 是设计成可以在 Sandbox 里用的，所以没法提供简单的访问任意文件的 API。

**Comment by w88975** [comment]
@xhacker  其实还有一个小问题

```html
<input type="file" />
```

在shell里面无效，这个不知道怎么解决

**Comment by xhacker** [comment]
@w88975: 我刚刚加了一下这个功能。你是想上传文件吧？我不确定能用，如果你测试了告诉我一下……
