### ISSUE TITLE
Backend Requests

### ISSUE THREAD

**Issue by fredfortier** [HackPlan/quark-shell-mac#45]
I like the idea of building a single UI which (hopefully) can work across multiple operation systems. However, it is not very useful to me if I cannot interface with the operation system. In Cordova for example, I would create a plug-in with an implementation per supported OS. How would you do that here?

**Comment by xhacker** [comment]
We don't have an official way to do that. However, you can modify the source code directly. Add a method in https://github.com/HackPlan/quark-shell-mac/blob/master/quark-shell/QSHWebViewDelegate.m, make sure it's not excluded (https://github.com/HackPlan/quark-shell-mac/blob/master/quark-shell/QSHWebViewDelegate.m#L67), then your method would be visible in JavaScript world via `quark.*`.
