### ISSUE TITLE
cannot find protocol declaration for webuidelegation

### ISSUE THREAD

**Issue by egoist** [HackPlan/quark-shell-mac#47]
![2015-10-08 4 11 41](https://cloud.githubusercontent.com/assets/8784712/10360922/4e832f0a-6dd7-11e5-90e0-5fbe409278a0.png)

OSX 10.10.4 ; XCode 6.4

**Comment by xhacker** [comment]
Can you use Xcode 7 and try again?

**Comment by egoist** [comment]
works on Xcode 7.0.1
