### ISSUE TITLE
Renaming app

### ISSUE THREAD

**Issue by chadwhitaker** [HackPlan/quark-shell-mac#50]
I don't have a heavy OS X / Xcode background, so I've found that renaming the app from "quark-shell" has proven difficult. Typically changing all identifiers and files from "quark" to my app's name has displayed several build errors.

Do you have any suggestions for renaming an app?

**Comment by xhacker** [comment]
You need to change the bundle identifier and bundle name. Please do the following:
* Change bundle identifier to a unique name, like in https://github.com/xhacker/quark-shell-mac/commit/0407c8d908d374406f114b6568574a5bfde055dd
* Change bundle name to what you want, like in https://github.com/xhacker/quark-shell-mac/commit/13ee583f24bf570af047f283452a94739d04d5f7

Let me know if you have more questions.
