### ISSUE TITLE
How to define notification icon? 

### ISSUE THREAD

**Issue by basiclaser** [HackPlan/quark-shell-mac#51]
I successfully set the application icons using an 'AppIcon' set in images.xcassets 
The system notification doesn't use any icons though, just the default 'blank' icon. 
How can I set it? 
Thanks! I love this project.

**Comment by xhacker** [comment]
Have you provided all the sizes? I added some sample icons in 4c0dda69379a52d655389f9943c67a69619cf9c4 and it works on my machine. If it doesn’t show, try killing `Notification Center` in Activity Monitor to clear cache.

**Comment by basiclaser** [comment]
Thanks a lot, I will try this.
